---
networks:
  chocolab:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  # chocoserver:
  #   build: coreserver
  #   container_name: chocoserver
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   environment:
  #     - DOCKER=true
  #   hostname: chocoserver
  #   networks:
  #     chocolab:
  #       ipv4_address: 172.20.0.10
  #   ports:
  #     - '55986:5986'
  #     - '13900:139'
  #     - '8080:80'
  #   tty: true
  # client:
  #   build: coreserver
  #   container_name: client
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   environment:
  #     - DOCKER=true
  #   hostname: client
  #   networks:
  #     chocolab:
  #       ipv4_address: 172.20.0.11
  #   ports:
  #     - '55987:5986'
  #   tty: true
  nexus:
    build: nexus
    container_name: nexus
    hostname: nexus
    networks:
      chocolab:
        ipv4_address: 172.20.0.12
    tty: true
